### ISSUE TITLE
Brute Force Protection

### ISSUE THREAD

**Issue by sashaaro** [nelmio/NelmioSecurityBundle#107]
Reduce attacks by limiting login attempts.

**Comment by sstok** [comment]
There was a Bundle for this, but it's discontinued 😢 https://github.com/codeconsortium/CCDNUserSecurityBundle

**Comment by apfz** [comment]
@sstok. that was one of my favorite bundles. 

can this be integrated?

**Comment by sstok** [comment]
No idea, I has not been updated for a while so it needs work. It depends if the maintainers of NelmioSecurityBundle want to integrate this.

I don't have time atm to fork the bundle and maintain it.

**Comment by cordoval** [comment]
leaving these link here:

https://github.com/metaclass-nl/MetaclassAuthenticationGuardBundle

**Comment by sashaaro** [comment]
Probably feature will be included in symfony https://github.com/symfony/symfony/pull/37444
