### ISSUE TITLE
X-Frame-Options value "ALLOW FROM uri" is misspelled

### ISSUE THREAD

**Issue by timdierolf** [nelmio/NelmioSecurityBundle#110]
The value for X-Frame-Options `ALLOW FROM uri` is misspelled. Instead, it should be `ALLOW-FROM uri` (see https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet#Defending_with_X-Frame-Options_Response_Headers). 

This is especially needed in browsers not supporting CSP 2.0 and its `frame-ancestors` directive like IEs (http://caniuse.com/#feat=contentsecuritypolicy2).

**Comment by romainneutron** [comment]
Hello, thanks for reporting.
This has been addressed in #111.
