### ISSUE TITLE
HTTP_X_FORWARDED_PROTO not handling at all

### ISSUE THREAD

**Issue by firatagdas** [nelmio/NelmioSecurityBundle#115]
I 'm currently using AWS and my hosts SSL handling done by AWS. So when I use forced_ssl, ForcedSslListener simply does redirect loop to same domain which is not expected. Can you add a proper handling for that?

**Comment by Seldaek** [comment]
You need to configure the Request headers that symfony trusts.

I use this for AWS application load balancer, which does SSL termination, in `app.php`:

```
Request::setTrustedProxies([$_SERVER['REMOTE_ADDR']]);
Request::setTrustedHeaderName(Request::HEADER_FORWARDED, '');
Request::setTrustedHeaderName(Request::HEADER_CLIENT_IP, 'X_FORWARDED_FOR');
Request::setTrustedHeaderName(Request::HEADER_CLIENT_HOST, '');
Request::setTrustedHeaderName(Request::HEADER_CLIENT_PROTO, 'X_FORWARDED_PROTO');
Request::setTrustedHeaderName(Request::HEADER_CLIENT_PORT, 'X_FORWARDED_PORT');
```

**Comment by firatagdas** [comment]
Thank you so much. It worked :) I didn't know this can be solved with symfony.
