### ISSUE TITLE
[Question] Deprecate PHP 5.3

### ISSUE THREAD

**Issue by romainneutron** [nelmio/NelmioSecurityBundle#120]
PHP 5.3 is not maintained, what about dropping support to this version to avoid writing compatible code ?

ie : `$that` injection

**Comment by romainneutron** [comment]
There's actually a comment about dropping support for old symfony and PHP version in https://github.com/nelmio/NelmioSecurityBundle/pull/106#issuecomment-265128788

**Comment by pulzarraider** [comment]
👍 for dropping support for php 5.3

**Comment by franmomu** [comment]
Support for PHP < 7.4 has been dropped in `3.0`
