### ISSUE TITLE
Unrecognized option "referrer_policy"

### ISSUE THREAD

**Issue by mysiar** [nelmio/NelmioSecurityBundle#126]
I can't figure it out why it doesn't work
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "referrer_policy" under "nelmio_security"
```

**Comment by romainneutron** [comment]
That's weird, it's tested. Could you copy/paste here your `composer.json` dependency constraint related to nelmio/security-bundle?

**Comment by mysiar** [comment]
It works now in the latest release. Didn't work in that release when I posted the problem
