### ISSUE TITLE
Csp impssible with twig 2.0

### ISSUE THREAD

**Issue by theoboldt** [nelmio/NelmioSecurityBundle#129]
Requirements of `"nelmio/security-bundle": "^2.1"` allow the bundle to be installed with `"twig/twig": "^2.1"`. Unfortunately, NelmioSecurityBundle seems not yet to be ready to be used with twig 2.x. 

As soon as I add the following to my configuration
```
nelmio_security:
    csp:
        enabled: true
```

and access a page which has `{% cspscript %}<script>//...</script>{% endcspscript %}` code fragment in it, the following exception is thrown: `Type error: Argument 1 passed to Nelmio\SecurityBundle\Twig\Node\CSPNode::__construct() must be an instance of Twig_NodeInterface, instance of Twig_Node given, called in .../vendor/nelmio/security-bundle/Twig/TokenParser/AbstractCSPParser.php on line 43
`

A quick look in the related classes proved that transmitted `CSPNode extends \Twig_Node`. While in twig 1.6 `Twig_Node implements Twig_NodeInterface` as expected, in twig 2.0 `Twig_Node implements Countable, IteratorAggregate` only. 

I have no idea why this changed in twig 2.0, possibly this is a bug in twig instead of nelmio/NelmioSecurityBundle. If not, nelmio/NelmioSecurityBundle should correct the requirements to not use twig 2.0.

**Comment by sstok** [comment]
Replacing this line: 

https://github.com/nelmio/NelmioSecurityBundle/blob/master/Twig/Node/CSPNode.php#L19
`public function __construct(\Twig_NodeInterface $body, $lineno, $tag, $directive, $sha = null)` with `public function __construct(\Twig_Node $body, $lineno, $tag, $directive, $sha = null)` should this.

And see something else, this bundle doesn't use the new RuntimeLoader which could improve performance 👍

**Comment by romainneutron** [comment]
Hello, thanks for reporting this, it should be fixed asap with https://github.com/nelmio/NelmioSecurityBundle/pull/130

@sstok Thanks for mentioning the RuntimeLoader, will work on it in an upcoming PR
