### ISSUE TITLE
[CSP] Allow nonce passed through header (to support Turbolinks/PJAX)

### ISSUE THREAD

**Issue by ruudk** [nelmio/NelmioSecurityBundle#136]
We are running a Symfony2 application with Turbolinks and want to use CSP. When we use the `csp_nonce()` method to generate a nonce, it will be different for every request. But since we use Turbolinks, navigating to other pages will just load the new HTML through AJAX and embed it in the current document. When a new page includes a `<script>` or `<style>` tag it will be blocked.

So I was thinking about the following solution:

In `ContentSecurityPolicyListener`: 
```php
    public function onKernelRequest(GetResponseEvent $event)
    {
        // ..

        if ($event->getRequest()->headers->has('X-CSP-Nonce')) {
            // @todo maybe add some regex validation
            $this->nonce = $event->getRequest()->headers->get('X-CSP-Nonce');
        }
    }
```

Then in my HTML I set this:
```twig
<meta name="csp_nonce" content="{{ csp_nonce() }}">
```

And in my `app.js` I set something like this:
```js
    $.ajaxSetup({
        headers: {
            'X-CSP-NONCE': document.querySelector('meta[name="csp_nonce"]').getAttribute('content'),
        }
    })
```

This works, but what about security? Am I going to do something really stupid/bad?

**Comment by sstok** [comment]
For the meta you need `http-equiv` not `name` as this an HTTP header, if your not sure you test this with something that should fail in that situation, load a script without a proper nonce. Assuming this works or believing it works because someone says yes is a dangerous practice.

**Comment by romainneutron** [comment]
With #139 , you could `$container->get('nelmio_security.twig_extension')->getCSPNonce()`.

**Comment by romainneutron** [comment]
OH, you can currently do
```php
$container->get('nelmio_security.csp_listener')->getNonce()
```
And it's much more cleaner

**Comment by stof** [comment]
@romainneutron I don't think closing this is right. The request is not to allow reading the nonce, buit about setting it.

**Comment by florimondmanca** [comment]
I'm hitting a similar issue just now. Turbo Drive manipulates the DOM and inserts stylesheets as part of normal operation. It supports reading a nonce from `<meta name="nonce" />`.

The first obstacle I'm encountering is that Turbo uses the same nonce for both scripts and styles, but we seem to have those separate here (not sure I understand why that is, it seems there's history about this choice).

Second, this bundle applies a new nonce for each request/response cycle. This comment https://github.com/hotwired/turbo/issues/294#issuecomment-877842232 suggests doing similar to OP, i.e. sending the nonce read initially by Turbo as a header that the server-side nonce generator would read.

I managed to resolve to make things work _partially_ by doing two things.

First, apply the recommended Turbo patch:

```js
// Somewhere in main app js

// See: https://github.com/hotwired/turbo/issues/294#issuecomment-877842232
document.addEventListener('turbo:before-fetch-request', (event) => {
    event.detail.fetchOptions.headers['X-CSP-Nonce'] = document.querySelector('meta[name="csp-nonce"]').content;
});
document.addEventListener('turbo:before-cache', () => {
    document.querySelectorAll('script[nonce]').forEach((element) => {
        element.setAttribute('nonce', element.nonce);
    });
});
```

Second, override the nonce generator to have it reuse the nonce if present, like so:

```php
// src/Infrastructure/Security/NonceGenerator.php
<?php

declare(strict_types=1);

namespace App\Infrastructure\Security;

use Nelmio\SecurityBundle\ContentSecurityPolicy\NonceGenerator as ParentNonceGenerator;
use Nelmio\SecurityBundle\ContentSecurityPolicy\NonceGeneratorInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\Event\ResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;

class NonceGenerator implements NonceGeneratorInterface, EventSubscriberInterface
{
    private ?string $requestNonce = null;

    public function __construct(
        private readonly ParentNonceGenerator $parent,
    )
    {
    }

    public function generate(): string
    {
        if ($this->requestNonce) {
            return $this->requestNonce;
        } else {
            return $this->parent->generate();
        }
    }

    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::REQUEST => ['onKernelRequest', 400],
            KernelEvents::RESPONSE => 'onKernelResponse',
        ];
    }

    public function onKernelRequest(RequestEvent $event): void
    {
        if ($event->getRequest()->headers->has('X-CSP-Nonce')) {
            $this->requestNonce = $event->getRequest()->headers->get('X-CSP-Nonce');
        }
    }

    public function onKernelResponse(ResponseEvent $event): void {
        $this->requestNonce = null;
    }
}
```

Service declaration:

```yaml
services:
  # ...
  App\Infrastructure\Security\NonceGenerator:
    decorates: 'nelmio_security.nonce_generator'
    arguments: ['@.inner']
```

Now, on pages where I get CSP errors upon navigating, I can see that the `<meta name="csp-nonce" />` reuses the same nonce (before the patch, it would send a new nonce). I also checked that my custom nonce generator is called with a `dd()` call.

Unfortunately, the CSP errors didn't go away, even though the `csp-nonce` value and the nonce values in  the CSP header match. More investigation needed...

**Comment by ruudk** [comment]
Please open a new issue, don't reply in something from 2017.
