### ISSUE TITLE
Public-Key-Pins

### ISSUE THREAD

**Issue by DavidGarciaCat** [nelmio/NelmioSecurityBundle#140]
Hello,

Is there a way to set-up the `Public-Key-Pins` header?
I cannot see it reading the docs at `README.md` file.

Thanks!

**Comment by Seldaek** [comment]
Nope.. and I'm not sure it's worth adding as per https://blog.qualys.com/ssllabs/2016/09/06/is-http-public-key-pinning-dead

**Comment by Seldaek** [comment]
Also, duplicate of #43 :)

**Comment by DavidGarciaCat** [comment]
👍 I was asking based on the fact that projects like GitHub are providing this header too, we can check it here https://securityheaders.io/?q=https%3A%2F%2Fgithub.com%2F

Thanks for the quick reply!
