### ISSUE TITLE
Strict-Transport-Security header is added to non-secure requests

### ISSUE THREAD

**Issue by Phobetor** [nelmio/NelmioSecurityBundle#147]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) "The Strict-Transport-Security header is ignored by the browser when your site is accessed using HTTP".
[hstspreload.org](https://hstspreload.org) emits a "Warning: Unnecessary HSTS header over HTTP" when submitting a domain that delivers an HSTS header via HTTP.

Therefore the HSTS header should no be added to non-secure requests.

**Comment by romainneutron** [comment]
You should therefore disable the configuration on the website. Why enabling HSTS on an http website?

**Comment by Phobetor** [comment]
@romainneutron I am not sure, if I unterstand you. The webserver is of course accessible via non-tls and tls. The symfony instance answers both request types. The `forced_ssl.enabled: true` option of this bundle redirects users from non-tls to tls. The only remaining issue ist, that the HSTS header is set in both versions but should only be set on tls. And that is what the pull request changes.
