### ISSUE TITLE
is there support for img-src sha hash on <img tag?

### ISSUE THREAD

**Issue by cordoval** [nelmio/NelmioSecurityBundle#162]
is there support for img-src sha hash on <img tag?
I was checking the listener and it is just <script and <link 
am i reading the specification wrong?

**Comment by sstok** [comment]
The purpose of this spec is to protect against hacked servers, both script and style (`<link`) allow the execution of JavaScript (yes that goes for stylesheets to).

But images do not execute any script (or at least they shouldn't there is an old attack technique were you could put some JavaScript in the EXIF data and MS IE would detect the image as an html document (yea for content sniffing https://github.com/nelmio/NelmioSecurityBundle#content-type-sniffing )).

**Comment by cordoval** [comment]
so i can move the image data base64 into a variable in js and use the script-src on that block rather than liberating :data on the other side

it seems the solution, thoughts?

**Comment by cordoval** [comment]
yeah i can work directly onto the dom and just pull it with generic trustable js

**Comment by cordoval** [comment]
thanks @sstok
