### ISSUE TITLE
tag for sf4.0?

### ISSUE THREAD

**Issue by cordoval** [nelmio/NelmioSecurityBundle#166]
the problem has been fixed and tests are passing

i am testing it on sf4.0 with dev-master@dev and it seems to be working fine, should we think about tagging it?

unless there is need to setPublic(true) on the extension but i doubt this bundle has public services to be used by the user.

**Comment by rpkamp** [comment]
Actually https://github.com/nelmio/NelmioSecurityBundle/issues/167 is blocking for SF4.

**Comment by rpkamp** [comment]
https://github.com/nelmio/NelmioSecurityBundle/issues/167 is fixed and merged to master, so it can be tagged for SF4 now :smiley:

**Comment by rpkamp** [comment]
Actually I see 2.5.0 was just released with SF4 support, so this ticket can be closed!
