### ISSUE TITLE
Adding Strict-Transport-Security to non-HTTPS connections

### ISSUE THREAD

**Issue by ndench** [nelmio/NelmioSecurityBundle#184]
I'm running my Symfony app behind an AWS load balancer so the HTTPS terminates at the load balancer and talks to my instance with HTTP. It would be great if this bundle allowed me to add the HSTS header without forcing an SSL connection. At the moment I'm working around this by adding the header in the nginx config, but it would be great to be able to configure all my security headers in one place.

**Comment by Seldaek** [comment]
If you configure the trusted headers correctly, symfony will know it is serving HTTPS pages even though the ELB is doing the SSL termination. In that case forced_ssl will not do a redirect. That's the better way to handle things IMO.

**Comment by Seldaek** [comment]
https://symfony.com/doc/current/deployment/proxies.html This is what I am referring to btw.

**Comment by ndench** [comment]
Awesome, I didn't realise that you could do that. Thanks!
