### ISSUE TITLE
Release 2.5.2

### ISSUE THREAD

**Issue by tgalopin** [nelmio/NelmioSecurityBundle#186]
Hello folks,

Thanks for the bundle, it seems really useful!

I wanted to try it but encountered an issue with random_compat 9.99. I saw the commit https://github.com/nelmio/NelmioSecurityBundle/commit/fdd8a68f8eabe04cafab7ae30d1667d81d01f292 fixed it. Is a 2.5.2 release possible so that I can install the bundle in stable :) ?

Thanks by advance!

**Comment by romainneutron** [comment]
2.6.0 has been released
