### ISSUE TITLE
Symfony 4.4 LTS - Erreur CSP

### ISSUE THREAD

**Issue by HeLLsSs** [nelmio/NelmioSecurityBundle#215]
Hi,

I have problem with this bundle on Symfony 4.4 :)

When i install, and configure it, i enabled CSP i have this error : 

Attempted to load class "Twig_Extension" from the global namespace.
Did you forget a "use" statement?

After, if i modify the bundle, i have same error with Token ...

Some one can help me ? Do you know alternative at this bundle for Security ?

Thanks, have a nice day.

**Comment by damienalexandre** [comment]
Hi,

Twig 3 support is added in #211. You did nothing wrong, you just have to wait for a new release of the bundle, or use Twig 2.

**Comment by romainneutron** [comment]
Fixed in version 2.9.0
