### ISSUE TITLE
Compatibility Twig3

### ISSUE THREAD

**Issue by Nathan-Riviere** [nelmio/NelmioSecurityBundle#216]
Hi,

NelmioSecurityBundle is not compatible with Twig 3.
Error :
> Attempted to load class "Twig_Extension" from the global namespace.
Did you forget a "use" statement?

![image](https://user-images.githubusercontent.com/53342864/73544673-ff94fc00-4439-11ea-8cd9-1d7424c19d6f.png)

Thanks !

**Comment by damienalexandre** [comment]
Twig 3 support is added in #211 :+1:

**Comment by romainneutron** [comment]
Fixed in version 2.9.0
