### ISSUE TITLE
Unexpected ')' in ContentSecurityPolicyController

### ISSUE THREAD

**Issue by andreheeke** [nelmio/NelmioSecurityBundle#228]
**Affected version**
2.10.0

**Description**
`Parse error: syntax error, unexpected ')' in /xxx/vendor/nelmio/security-bundle/Controller/ContentSecurityPolicyController.php on line 50`

https://github.com/nelmio/NelmioSecurityBundle/blob/master/Controller/ContentSecurityPolicyController.php#L50

**Comment by xabbuh** [comment]
sorry I messed this up in #227, #229 should fix it

**Comment by oexler** [comment]
When will there be a release with this fix?

**Comment by romainneutron** [comment]
Thanks for the report, I just released https://github.com/nelmio/NelmioSecurityBundle/releases/tag/v2.10.1 that fix this issue.
@xabbuh Sorry I did not see your PR, I pushed directly.

**Comment by xabbuh** [comment]
Thank you Romain! :)
