### ISSUE TITLE
Not compatible with Framework-Bundle 5.0

### ISSUE THREAD

**Issue by alcohol** [nelmio/NelmioSecurityBundle#231]
Framework-Bundle requires Event-Dispatcher, see changelog for v5:

https://github.com/symfony/event-dispatcher/blob/master/CHANGELOG.md#500

The following change breaks code in this bundle:

- The `Event` class has been removed in favor of `Symfony\Contracts\EventDispatcher\Event`.

~~The `Event` class was already deprecated since 4.3 btw. So I'm not sure why nobody reported this before :-(~~

**Comment by mvanduijker** [comment]
Part where it goes wrong: https://github.com/nelmio/NelmioSecurityBundle/blob/master/ContentSecurityPolicy/Violation/Event.php#L14

**Comment by alcohol** [comment]
I see #221 already addresses this :+1: just a matter of time then

**Comment by mvanduijker** [comment]
I think this one can be closed now https://github.com/nelmio/NelmioSecurityBundle/pull/221#issuecomment-800074318
