### ISSUE TITLE
Disable CSP for some URLs

### ISSUE THREAD

**Issue by randomsymbols** [nelmio/NelmioSecurityBundle#232]
Is it possible to disable CSP for certain URLs? For example www.site.com - CSP enabled, but for www.site.com/admin - CSP disabled?

I have this question because it is impossible to configure Symfony Sonata Admin bundle with CSP, and we have the bundle integrated into our web site.

**Comment by Seldaek** [comment]
Duplicate of https://github.com/nelmio/NelmioSecurityBundle/issues/206
