### ISSUE TITLE
Symfony 6 compatibility

### ISSUE THREAD

**Issue by xKZL** [nelmio/NelmioSecurityBundle#246]
Hello guys,

Is there any plan to make compatibility with Symfony 6 ?

Cheers,

**Comment by stephanvierkant** [comment]
Related question: what about dropping support for EOL-versions of PHP? Only 7.4, 8.0 and 8.1 are supported as of tomorrow. If so, #245 can be simplified as well.

And we can replace #122 by a PR that supports Symfony 4.4|^5.3.

**Comment by spackmat** [comment]
I tried it out with a local version, that works fine with the 6.0 versions of the required symfony-packages. Some deprecations pop up, when I use the bundle with Symfony 6.0.1 on PHP 8.0:

> Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "Nelmio\SecurityBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.

> Method "Symfony\Component\EventDispatcher\EventSubscriberInterface::getSubscribedEvents()" might add "array" as a native return type declaration in the future. Do the same in implementation "Nelmio\SecurityBundle\EventListener\ClickjackingListener" now to avoid errors or add an explicit @return annotation to suppress this message.

> Method "Symfony\Component\EventDispatcher\EventSubscriberInterface::getSubscribedEvents()" might add "array" as a native return type declaration in the future. Do the same in implementation "Nelmio\SecurityBundle\EventListener\ContentSecurityPolicyListener" now to avoid errors or add an explicit @return annotation to suppress this message.

> Method "Symfony\Component\EventDispatcher\EventSubscriberInterface::getSubscribedEvents()" might add "array" as a native return type declaration in the future. Do the same in implementation "Nelmio\SecurityBundle\EventListener\XssProtectionListener" now to avoid errors or add an explicit @return annotation to suppress this message.

> Method "Twig\TokenParser\TokenParserInterface::parse()" might add "Node" as a native return type declaration in the future. Do the same in implementation "Nelmio\SecurityBundle\Twig\TokenParser\AbstractCSPParser" now to avoid errors or add an explicit @return annotation to suppress this message.

> Method "Twig\TokenParser\TokenParserInterface::getTag()" might add "string" as a native return type declaration in the future. Do the same in implementation "Nelmio\SecurityBundle\Twig\TokenParser\AbstractCSPParser" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by pyrech** [comment]
FYI I just made a PR to add support for Symfony 6 and fix direct deprecation notices : https://github.com/nelmio/NelmioSecurityBundle/pull/249
