### ISSUE TITLE
[RFC] Remove Cookie Session Handler in 3.0

### ISSUE THREAD

**Issue by franmomu** [nelmio/NelmioSecurityBundle#270]
From docs: https://github.com/nelmio/NelmioSecurityBundle#cookie-session-handler

> You can configure the session handler to use a cookie based storage. There are various reasons to do this, but generally speaking unless you have a very good one you should avoid it.

I think we can remove it in version 3.0, apparently it's only about creating a [CookieSessionHandler](https://github.com/nelmio/NelmioSecurityBundle/blob/909030263fe995a2b66908b045b9ff7379cd18fe/src/Session/CookieSessionHandler.php) that the few users using this can implement in their projects (IMHO it doesn't fit in a `SecurityBundle`).

**Comment by Seldaek** [comment]
I'm not sure.. It's hard to tell how used this is, I guess typically people would do this with JWT in a cookie nowadays?

I think it's probably fine to remove, and see how many people complain.. It can always be added back if needed.
