### ISSUE TITLE
Request hasPreviousSession and Cookie Session Handler

### ISSUE THREAD

**Issue by dteoh** [nelmio/NelmioSecurityBundle#28]
I configured my app to use Cookie Session Handler and discovered that authentication started breaking. I kept getting "Your session has timed out, or you have disabled cookies.". I traced this issue down to [AbstractAuthenticationListener](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Security/Http/Firewall/AbstractAuthenticationListener.php#L142) and then to the [hasPreviousSession method of Request](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/HttpFoundation/Request.php#L715). I discovered that if I add:

``` yaml
framework:
    session:
        name: session
```

...the problem disappears. But doing this means that the browser is receiving two cookies named "session". The browser seems to be using the last `Set-Cookie: session=` when it picks which of the two to send back.

I am wondering if this is how this session handler is meant to be used, or if there is some extra configuration that needs to be done.

**Comment by rodush** [comment]
:+1: simply does not work at all with symfony 2.7
I just can not log in if encrypter/singer is enabled.. Debugged and ended up with the same result - cookies are removed from request, and onKernelResponse simply not getting called.
We use Redis to store our sessions.

**Comment by jayesbe** [comment]
Symfony 2.7 here. Same use case as rodush.

**Comment by aistis-** [comment]
Run into the same problem :disappointed:

**Comment by apfz** [comment]
same problem. symfony 3.

**Comment by thewilkybarkid** [comment]
Think we're hitting the same problem in Symfony 3 (using `signed_cookie`).

**Comment by cfoehrdes** [comment]
Is there any progress or some knowledge about a workaround for this issue? We are experiencing the same issue in a symfony 3.4 project.

**Comment by franmomu** [comment]
Closing the issue since `SessionCookieHandler` and `EncryptedCookieListener` have been removed in `3.0`, feel free to open a new issue if the problem persists.
