### ISSUE TITLE
make the log message for reported CSP violations configurable

### ISSUE THREAD

**Issue by ghost** [nelmio/NelmioSecurityBundle#32]
With CSP I can define different report-uri's for enforced and for reported CSP policies. It would make sense to also have different log messages (and log levels) for these two.

Normally I should test my CSP policies before I switch them to be enforced. However I could miss something. In that case I'd like to have an alert that I need to change my policy imediately.

This can be easily implemented by defining the same report controller two times with different arguments and make the message and log level configurable with constructor parameters.

**Comment by franmomu** [comment]
Closing as this is possible since https://github.com/nelmio/NelmioSecurityBundle/pull/119
