### ISSUE TITLE
Update the description of this GitHub repository

### ISSUE THREAD

**Issue by javiereguiluz** [nelmio/NelmioSecurityBundle#323]
The description still refers to "Symfony2". Maybe we can take inspiration from NelmioCorsBundle for a quick reword. Thanks!

![](https://user-images.githubusercontent.com/73419/219342966-5683cac4-619e-496d-b36b-1db9b350c114.jpg)

**Comment by franmomu** [comment]
👍 this should be @Seldaek

**Comment by Seldaek** [comment]
All done 👍🏻
