### ISSUE TITLE
Nonce is empty unless dump using twig

### ISSUE THREAD

**Issue by vdeville** [nelmio/NelmioSecurityBundle#340]
Hello,

Today i tested to add inline-nonce to all scripts. In Production mode no problem, but in dev mode if i not do `{% dump(csp_nonce('script')) %}` all the script have empty nonce

Do you have any idea about this problem ?

Thanks

**Comment by vdeville** [comment]
Example in html:
<img width="522" alt="Capture d’écran 2024-03-08 à 16 12 08" src="https://github.com/nelmio/NelmioSecurityBundle/assets/6104498/287553f4-087d-4296-b075-9cc7bee0aa38">
Incode: 
```html
<script type="text/javascript" nonce="{{ csp_nonce('script') }}" nonceTest="{{ csp_nonce('script') }}">
```

**Comment by vdeville** [comment]
Do dump before this script in twig:

```html
        {{ dump(csp_nonce('script')) }}
        <script type="text/javascript" nonce="{{ csp_nonce('script') }}" nonceTest="{{ csp_nonce('script') }}">
```

Result:
<img width="680" alt="Capture d’écran 2024-03-08 à 16 14 02" src="https://github.com/nelmio/NelmioSecurityBundle/assets/6104498/9367a511-ad92-49e1-ab67-6ba981c85d94">

**Comment by Seldaek** [comment]
This is normal https://stackoverflow.com/a/55673767/6512

You can check the view-source of the page to verify nonces, do not use the web inspector.

**Comment by vdeville** [comment]
Thanks for your reply, i don't really understand why in dev or prod env some scripts was not loaded or loaded, for example in dev mode googlemap put eval error in javascript, not in production (same config, same loaded url etc)
Thanks
