### ISSUE TITLE
[3.2.0] The report-uri directive has been deprecated

### ISSUE THREAD

**Issue by directsoftware** [nelmio/NelmioSecurityBundle#341]
Hello,

I was conducting DAST tests, which returned me the following message: "The report-uri directive has been deprecated in favor of the new report-to directive."
Do you have plans to introduce support for the "report-to" directive? Because currently, I don't see such a parameter for configuration.

**Comment by Seldaek** [comment]
No plans, but PRs welcome, as resources to maintain this bundle are very limited.

**Comment by martijnc** [comment]
Is there interest from the bundle maintainers to also support the [Reporting API ](https://www.w3.org/TR/reporting-1/)`Reporting-Endpoints` header? While not technically a security header, it is supported for reporting by a number of other security headers (CSP,  COOP, COEP, Document Policy, ...).  The header is just a list of named endpoints.
