### ISSUE TITLE
support public key pinning header

### ISSUE THREAD

**Issue by jrobeson** [nelmio/NelmioSecurityBundle#43]
Spec: http://tools.ietf.org/html/draft-ietf-websec-key-pinning-20
A simpler writeup: https://raymii.org/s/articles/HTTP_Public_Key_Pinning_Extension_HPKP.html
Mozilla's take: https://blog.mozilla.org/security/2014/09/02/public-key-pinning/

I might give it a go at implementation, but currently it only truly works in chrome, and even then, we'll need to wait for the next stable build for it to work correctly alongside HSTS due to https://code.google.com/p/chromium/issues/detail?id=444511

I'd submit a first draft at a PR, but i wonder where it should go.

**Comment by Seldaek** [comment]
I wonder if this really makes sense in the bundle, given the SSL cert stuff is configured at the webserver I feel like this belongs there more than at the application level..

**Comment by Seldaek** [comment]
Well no ok I guess since it is just about pinning the CAs maybe it's fine here. It doesn't seem to require much code anyway so maybe just adding a new option to the HSTS / ForcedSslListener makes sense?

**Comment by willdurand** [comment]
:+1:

> It doesn't seem to require much code anyway so maybe just adding a new option to the HSTS / ForcedSslListener makes sense?

Yes, this makes sense.

**Comment by romainneutron** [comment]
FYI https://blog.qualys.com/ssllabs/2016/09/06/is-http-public-key-pinning-dead

**Comment by christiaan** [comment]
FYI https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ

Chrome is dropping support for HPKP and it appears Safari and Edge will also.

Here some more background info on the problems with it https://scotthelme.co.uk/im-giving-up-on-hpkp/

**Comment by Seldaek** [comment]
Yup I think rather close this..
