### ISSUE TITLE
how to handle child-src in CSP?

### ISSUE THREAD

**Issue by jrobeson** [nelmio/NelmioSecurityBundle#49]
frame-src is deprecated in favor of child-src
see:  https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives

How do you think we should handle this? child-src is only implemented in CSP Level 2 and also covers web workers, so we can't simply replace frame-src. 

Should we just allow both to operate independently?

**Comment by Seldaek** [comment]
For BC I guess we should allow both independently but disallow having both set? And if child-src is set I guess we should set frame-src to the same value for now until browsers caught up.

**Comment by jrobeson** [comment]
but webworkers are handled in child-src, but not frame-src, so you can't set them to the same value.

**Comment by Seldaek** [comment]
As far as I understand child-src covers frame-src+some stuff, so if we set both supporting browsers should only read child-src and the others will read frame-src no? Aren't they both just a list of allowed sources?

**Comment by jrobeson** [comment]
it's the + some stuff that i'm worried about, we can't set that in frame-src

**Comment by Seldaek** [comment]
Well I don't really see what could go wrong as both child-src and frame-src are just configured with a list of allowed sources. It just means that CSP1 browsers would allow your webworker urls to be used as iframes but this would happen in CSP2 browsers as well anyway as child-src encompasses both frames and webworkers.

**Comment by romainneutron** [comment]
Fixed by #84, to be released in version 2.0.0
