### ISSUE TITLE
Inactive scope ("request")

### ISSUE THREAD

**Issue by spbentz** [nelmio/NelmioSecurityBundle#66]
I have an InactiveScopeException on the "nelmio_security.external_redirect_listener". It seems it comes from the "scope: request" because when I remove it, "app/console debug:event-dispatcher" is OK. I tryed using the"request_stack" service to fix it (@see http://symfony.com/blog/new-in-symfony-2-4-the-request-stack) without success.

**Comment by Seldaek** [comment]
Which symfony version are you using?

**Comment by spbentz** [comment]
Hello Jordi,

 

I’m running the latest version (SF 2.7.3) and I had the previous when writing the message.

 

Stéphane

 

De : Jordi Boggiano [mailto:notifications@github.com] 
Envoyé : samedi 1 août 2015 18:29
À : nelmio/NelmioSecurityBundle <NelmioSecurityBundle@noreply.github.com>
Cc : Stéphane Paul Bentz <stephane.bentz@gmail.com>
Objet : Re: [NelmioSecurityBundle] Inactive scope ("request") (#66)

 

Which symfony version are you using?

**Comment by Seldaek** [comment]
Ok but then request_stack should be available.

**Comment by spbentz** [comment]
I still have this :

[event_dispatcher] Registered listeners by event
                                                                               
  [Symfony\Component\DependencyInjection\Exception\InactiveScopeException]     
  You cannot create a service ("nelmio_security.clickjacking_listener") of an  
   inactive scope ("request").

Same problem with  "nelmio_security.content_type_listener" and "nelmio_security.content_type_listener".  

If I remove "scope: request" in the services, it's OK : 

services:
    nelmio_security.clickjacking_listener:
        // scope: request
        class: Nelmio\SecurityBundle\EventListener\ClickjackingListener
        arguments:
            - %nelmio_security.clickjacking.paths%
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

**Comment by spbentz** [comment]
I tried to solve the problem by removing services without success. To be more precise, the error is displayed only when running "app/console debug:event-dispatcher kernel.response"

**Comment by pculka** [comment]
This seems to still be an issue with Symfony 2.7. Any fix ?

**Comment by Seldaek** [comment]
Can you share your bundle config? Then I might have a chance to repro.
Because it works here on 2.8..

**Comment by pculka** [comment]
http://pastebin.com/kGVgTEGB here it is

produced error:

```
[vagrant@www01 current]$ php app/console debug:event-dispatcher

Registered Listeners Grouped by Event
=====================================



  [Symfony\Component\DependencyInjection\Exception\InactiveScopeException]
  You cannot create a service ("nelmio_security.content_type_listener") of an inactive scope ("request").
```

which is kinda awkward

**Comment by pculka** [comment]
as soon as I remove the content_type.nosniff: true, it works

**Comment by Seldaek** [comment]
@pculka do you still get this with the latest version of the bundle? Because we removed the whole scope stuff as it was incompatible with sf3.
