### ISSUE TITLE
[Feature request] The clickjacking listener should skip its logic if X-Frame-Options is already set

### ISSUE THREAD

**Issue by stof** [nelmio/NelmioSecurityBundle#71]
This would allow a controller to set it explicitly when it knows it is intended to be used in an iframe. See https://github.com/symfony/swiftmailer-bundle/issues/114 for a case where it would be useful (otherwise enabling NelmioSecurityBundle would break SwiftmailerBundle profiler until they whitelist it, once we have this feature)

**Comment by Seldaek** [comment]
True, good idea, in general this probably applies to other features as well.

**Comment by stof** [comment]
Yeah, I simply haven't checked how other features are impacted.

Finding a way for the controller to allow any origin for the iframe would be hard though (as this is allowed by the absence of header)

**Comment by Seldaek** [comment]
That's true, I guess if you say `X-Frame-Options: ALLOW` or such all browsers will fail to parse it and just treat it as if it didn't exist.
