### ISSUE TITLE
Is it an error in config?

### ISSUE THREAD

**Issue by pavanvamsi3** [nelmio/NelmioSecurityBundle#80]
```
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]   
  Unrecognized options "hosts, content_types" under "nelmio_security.csp.report"
```

I'm using the default configuration. Whenever I'm clearing symfony app's cache, I find this error.

**Comment by Seldaek** [comment]
That's weird, I don't see this here. I'm gonna need more details to have any hopes of helping you here I think.

**Comment by pavanvamsi3** [comment]
I've just install the bundle in my Symfony app and when I'm running `app/console cache:clear` I get this.

**Comment by romainneutron** [comment]
Could you copy/paste your nelmio configuration?

**Comment by peternijssen** [comment]
I have the same error after copy-pasting the max security settings from the README file.

**Comment by romainneutron** [comment]
This is an error in configuration example, please have a look at #89
